apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
  labels:
    app: data-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels:
        app: data-service
    spec:
      containers:
      - name: data-service
        image: gcr.io/nansi8-217516/data-service
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 0.1
            memory: 128Mi
          limits:
            cpu: 0.1
            memory: 256Mi