apiVersion: v1
kind: ConfigMap
metadata:
  name: data-service-config
data:
  data-nodes: 2
  checksum-nodes: 2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
  labels:
    app: data-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels:
        app: data-service
    spec:
      containers:
      - name: data-service
        image: gcr.io/nansi8-217516/data-service
        env:
        - name: DATA_NODES
          valueFrom:
            configMapKeyRef:
              name: data-service-config
              key: data-nodes
        - name: CHECKSUM_NODES
          valueFrom:
            configMapKeyRef:
              name: data-service-config
              key: checksum-nodes
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 0.1
            memory: 128Mi
          limits:
            cpu: 0.1
            memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: data-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: data-service
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: data-service
  annotations:
    kubernetes.io/ingress.global-static-ip-name: data-service-ip
  labels:
    app: data-service
spec:
  backend:
    serviceName: data-service
    servicePort: 80