apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: data-storage
spec:
  serviceName: data-storage-service
  selector:
    matchLabels:
      app: data-storage
  replicas: 4
  template:
    metadata:
      labels:
        app: data-storage
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-data-storage
        image: redis
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - mountPath: /data
          name: data-storage-volume
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
  volumeClaimTemplates:
  - metadata:
      name: data-storage-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi